### PR TITLE
Remove blank line

### PR DESCRIPTION
**Pull request by 7k5x**
내가 이렇게까지 해주는데 내맘을 몰라주는 장협쿤...ㅠㅠ

### CODE REVIEW

**Comment by Jhyub** [comment]
this pr does nothing; you should check if your changes are made correctly before making a request
also, don't make meaningless PRs just to talk with me

**Comment by 7k5x** [comment]
then read my email 😥

**Comment by 7k5x** [comment]
did you block me?😟

**Comment by 7k5x** [comment]
This does something; I removed spaces to remove a useless and dirty blank line in README

**Pull request closed without merging**
